# docker-compose.yml

version: '3.8'

services:
  migration:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    entrypoint: /bin/bash
    command: -c 'while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head'
    environment:
      - DB_URI=postgresql://fastapi_traefik:fastapi_traefik@db:5432/fastapi_traefik
    depends_on:
      - db
    networks:
      - web

  fastapi:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8008:8000"
    environment:
      - DB_URI=postgresql://fastapi_traefik:fastapi_traefik@db:5432/fastapi_traefik
    depends_on:
      - db
      - migration
    networks:
      - web

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=fastapi_traefik
      - POSTGRES_PASSWORD=fastapi_traefik
      - POSTGRES_DB=fastapi_traefik
    networks:
      - web


  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - web

volumes:
  postgres_data:

networks:
  web:

